### ISSUE TITLE
Filtering v1/metrics/network by relayer does not work

### ISSUE THREAD

**Issue by brandoncurtis** [0xTracker/0x-tracker-api#125]
Looking at the site, I noticed that the pages for each relayer showed the same network stats plots regardless of which relayer was selected:

- https://0xtracker.com/relayers/radar-relay
- https://0xtracker.com/relayers/paradex

Taking a look at the API, I realized that it was returning the same values regardless of the relayerId:

- https://api.0xtracker.com/v1/metrics/network?period=month&relayerId=paradex
- https://api.0xtracker.com/v1/metrics/network?period=month

I also noticed that the frontend is calling into the API with relayerIds that don't match the ones defined in the API:
- https://api.0xtracker.com/v1/metrics/network?period=month&relayerId=radarRelay
- https://github.com/0xTracker/0x-tracker-api/blob/master/src/relayers/get-all-relayers.js

```
  radarRelay: {
    imageUrl: 'https://0xtracker.com/assets/logos/radar-relay.png',
    lookupId: 7,
    name: 'Radar Relay',
    slug: 'radar-relay',
    url: 'https://radarrelay.com',
  },
```

Taking a look at how this filtering is supposed to function:

- https://github.com/0xTracker/0x-tracker-api/blob/master/src/relayers/get-all-relayers.js
- https://github.com/0xTracker/0x-tracker-api/blob/master/src/metrics/get-network-metrics.js

```
const getNetworkMetrics = async (period, tokens, { relayerId } = {}) => {
  const { dateFrom, dateTo } = getDatesForTimePeriod(period);
  const metricInterval = getMetricIntervalForTimePeriod(period);
  const optionalCriteria = _.compact([_.isNumber(relayerId) && { relayerId }]);
  const query = _.merge(
    { date: { $gte: dateFrom, $lte: dateTo } },
    ...optionalCriteria,
  );
```

**Comment by cbovis** [comment]
Thanks for the heads up @brandoncurtis. It turns out the relayer argument should have been sent to the endpoint as `relayer` rather than `relayerId`. It was broken in a somewhat recent refactoring.

I've pushed out a fix.
